# Generated by Django 4.1.3 on 2023-02-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="Items",
        ),
    ]
