# Generated by Django 4.1.3 on 2023-02-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0002_rename_article_items"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Items",
            new_name="Item",
        ),
    ]
