# Generated by Django 4.1.3 on 2023-02-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0004_rename_item_item_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="name",
            new_name="item",
        ),
    ]
