# Generated by Django 4.1.3 on 2023-02-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0005_rename_name_item_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="item",
            new_name="name",
        ),
    ]
