# Generated by Django 4.1.3 on 2023-02-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0007_tag_item_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
