# Generated by Django 4.1.3 on 2023-02-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0009_tag_item_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
