# Generated by Django 4.1.3 on 2023-02-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0013_alter_tag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
