# Generated by Django 4.1.3 on 2023-03-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0015_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_time",
            field=models.DateTimeField(),
        ),
    ]
