# Generated by Django 4.1.3 on 2023-03-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0020_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="venue_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shopping_list.tag",
            ),
        ),
    ]
