# Generated by Django 4.1.3 on 2023-03-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0021_alter_order_venue_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_num",
            field=models.IntegerField(default="", max_length=100),
        ),
    ]
