# Generated by Django 4.1.3 on 2023-03-05 21:15

from django.db import migrations

def populate_tags(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Tag = apps.get_model('shopping_list', 'Tag')
    if Tag.object.count() == 0:
        Tag.objects.create(name='טיב טעם', color='success')
        Tag.objects.create(name='נוי השדה', color='secondary')
        Tag.objects.create(name='ג׳ונגל', color='info')

class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0025_rename_date_item_created_at"),
    ]

    operations = [populate_tags]
